version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - KINDE_ISSUER_URL=${KINDE_ISSUER_URL}
      - KINDE_CLIENT_ID=${KINDE_CLIENT_ID}
      - KINDE_CLIENT_SECRET=${KINDE_CLIENT_SECRET}
      - KINDE_REDIRECT_URI=https://roamingroomies.dhruvanpatel.dev/api/callback
      - KINDE_LOGOUT_REDIRECT_URI=https://roamingroomies.dhruvanpatel.dev
      - KINDE_DOMAIN=${KINDE_DOMAIN}
      - FRONTEND_URL=https://roamingroomies.dhruvanpatel.dev
    volumes:
      - ./client/dist:/app/client/dist
      - ./server:/app/server
    restart: unless-stopped
    command: bun run server/index.ts

    healthcheck:
      test: ["CMD", "curl", "-f", "https://roamingroomies.dhruvanpatel.dev/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s 