CREATE TABLE "roommate_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"age" integer NOT NULL,
	"gender" text NOT NULL,
	"occupation" text,
	"sleep_schedule" text,
	"cleanliness_level" integer,
	"dietary_preferences" text,
	"smoking_tolerance" boolean DEFAULT false,
	"pet_tolerance" boolean DEFAULT false,
	"alcohol_tolerance" boolean DEFAULT false,
	"interests" text[],
	"personality_traits" text,
	"desired_room_type" text,
	"max_rent" numeric,
	"preferred_locations" text[],
	"move_in_date" date,
	"minimum_stay" integer,
	"bio" text,
	"profile_image_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "roommate_users_email_unique" UNIQUE("email")
);
